### PR TITLE
Fix #4

### LINKED ISSUE #4: no matching file entry case
It looks as though if there is no matching entry, the callback will never be made. I think we'll need to do a zip.on('end', ...) and if the cb hasn't already been called, call it back with an error of not found.

### PR DESCRIPTION
**Pull request by dweinstein**
- closes #4

### CODE REVIEW

**Comment by dweinstein** [comment]
@juliangruber could you add me as an owner (for npm) by any chance so I can release a new version please? Thanks!

**Comment by dweinstein** [comment]
@juliangruber ping

**Comment by juliangruber** [comment]
@dweinstein added you

**Comment by dweinstein** [comment]
thanks!

**Comment by dweinstein** [comment]
- ipa-extract-info@1.2.2

**Pull request merged**
