### PR TITLE
Updates per npm audit

### PR DESCRIPTION
**Pull request by dki**
Updated the following per `npm audit`:
- `minimist` to v1.2.5
- `static-eval` to v2.1.0
- `path-parse` to v1.0.7
- `plist` to v3.0.4
- `semistandard` to v16.0.1

### CODE REVIEW

**Comment by dki** [comment]
Found a bug, please hold on review

**Comment by dki** [comment]
False alarm, good to review.

**Comment by dweinstein** [comment]
thanks

**Comment by dweinstein** [comment]
released as `ipa-extract-info@1.2.6`

**Pull request merged**
